// Thème visuel + navigation par rôle. Couleur d'accent canonique par rôle (une seule par
// rôle, précisée explicitement par le client) : Admin #4f46e5 · Université #7c3aed ·
// Entreprise #0891b2 · Banque #2563eb · Notaire #059669 · Utilisateur #4f46e5.
export const ROLE_THEMES = {
  ADMIN: {
    badge: null,
    roleLabel: 'Super Administrateur',
    accent: '#4f46e5',
    menu: [
      { label: 'Tableau de bord', icon: 'dashboard', path: '/admin' },
      { section: 'GESTION DES IDENTITÉS' },
      { label: 'DID & Identités', icon: 'badge', path: '/admin/dids' },
      { label: 'Profils & Rôles', icon: 'groups2', path: '/admin/roles' },
      { section: 'TITRES & DOCUMENTS' },
      { label: 'Titres fonciers', icon: 'description', path: '/admin/land-titles' },
      { label: 'Diplômes', icon: 'school', path: '/admin/diplomas' },
      { label: 'Attestations', icon: 'description', path: '/admin/attestations' },
      { label: 'Transferts', icon: 'sync_alt', path: '/admin/transfers' },
      { section: 'SYSTÈME' },
      { label: 'Demandes & Workflows', icon: 'assignment', path: '/admin/workflows' },
      { label: 'Paramètres', icon: 'settings', path: '/admin/settings' },
      { label: "Journal d'activités", icon: 'receipt_long', path: '/admin/journal' },
    ],
  },
  ISSUER: {
    badge: null,
    roleLabel: 'Administrateur',
    accent: '#7c3aed',
    institution: true,
    menu: [
      { label: 'Tableau de bord', icon: 'dashboard', path: '/university' },
      { section: 'IDENTITÉ ACADÉMIQUE' },
      { label: 'Étudiants', icon: 'groups', path: '/university/students' },
      { label: 'Diplômes & Certificats', icon: 'description', path: '/university/diplomas' },
      { label: 'Attestations', icon: 'workspace_premium', path: '/university/attestations' },
      { label: 'Établir DID', icon: 'badge', path: '/university/create-did' },
      { section: 'ADMINISTRATION' },
      { label: 'Utilisateurs', icon: 'groups', path: '/university/users' },
      { label: 'Vérifier un document', icon: 'verified', path: '/university/verify' },
      { label: 'Demandes de vérification', icon: 'fact_check', path: '/university/requests' },
      { section: 'SYSTÈME' },
      { label: 'Paramètres', icon: 'settings', path: '/university/settings' },
      { label: "Journal d'activités", icon: 'receipt_long', path: '/university/journal' },
    ],
  },
  VERIFIER: {
    badge: 'ENTREPRISE',
    roleLabel: 'Responsable RH',
    accent: '#0891b2',
    menu: [
      { label: 'Tableau de bord', icon: 'dashboard', path: '/company' },
      { section: 'IDENTITÉ' },
      { label: 'Établir DID', icon: 'badge', path: '/company/create-did' },
      { label: 'Attestation employeur', icon: 'description', path: '/company/issue' },
      { section: 'ADMINISTRATION' },
      { label: 'Employés', icon: 'groups', path: '/company/employees' },
      { label: 'Rôles & Permissions', icon: 'groups2', path: '/company/roles' },
      { label: 'Vérifier un document', icon: 'verified', path: '/company/verify' },
      { label: 'Demandes de vérifications', icon: 'fact_check', path: '/company/requests' },
      { section: 'SYSTÈME' },
      { label: 'Paramètres', icon: 'settings', path: '/company/settings' },
      { label: "Journal d'activités", icon: 'receipt_long', path: '/company/journal' },
    ],
  },
  BANK: {
    badge: 'BANQUE',
    roleLabel: 'Responsable Conformité',
    accent: '#2563eb',
    menu: [
      { label: 'Tableau de bord', icon: 'dashboard', path: '/bank' },
      { section: 'CLIENTS' },
      { label: 'Établir DID', icon: 'badge', path: '/bank/create-did' },
      { label: 'Demandes de prêt', icon: 'request_quote', path: '/bank/loans' },
      { label: 'Clients', icon: 'groups', path: '/bank/clients' },
      { section: 'ADMINISTRATION' },
      { label: 'Vérifier un document', icon: 'verified', path: '/bank/verify' },
      { section: 'SYSTÈME' },
      { label: "Journal d'activités", icon: 'receipt_long', path: '/bank/journal' },
      { label: 'Paramètres', icon: 'settings', path: '/bank/settings' },
    ],
  },
  NOTARY: {
    badge: 'NOTAIRE',
    roleLabel: 'Notaire',
    accent: '#059669',
    menu: [
      { label: 'Tableau de bord', icon: 'dashboard', path: '/state' },
      { section: 'ACTES NOTARIÉS' },
      { label: 'Enregistrer un titre', icon: 'description', path: '/state/register' },
      { label: 'Transferts en cours', icon: 'sync_alt', path: '/state/transfers' },
      { label: 'Signatures en attente', icon: 'fact_check', path: '/state/signatures' },
      { label: 'Liste des actes', icon: 'menu_list', path: '/state/acts' },
      { section: 'CONTRÔLES' },
      { label: 'Vérifications', icon: 'groups2', path: '/state/verifications' },
      { label: 'Vérifier un document', icon: 'verified', path: '/state/verify' },
      { section: 'SYSTÈME' },
      { label: "Journal d'activités", icon: 'receipt_long', path: '/state/journal' },
      { label: 'Paramètres', icon: 'settings', path: '/state/settings' },
    ],
  },
  USER: {
    badge: 'UTILISATEUR',
    badgeSoft: true,
    roleLabel: 'Utilisateur',
    accent: '#4f46e5',
    menu: [
      { label: 'Tableau de bord', icon: 'dashboard', path: '/dashboard' },
      { label: 'Mon identité', icon: 'badge', path: '/profile' },
      {
        label: 'Mes documents', icon: 'folder', expandable: true,
        children: [
          { label: 'Titres fonciers', icon: 'description', path: '/dashboard/land-titles' },
          { label: 'Diplômes', icon: 'school', path: '/dashboard/diplomas' },
          { label: 'Attestations', icon: 'workspace_premium', path: '/dashboard/attestations' },
          { label: "Pièces d'identité", icon: 'badge', path: '/dashboard/id-cards' },
        ],
      },
      { label: 'Mes partages', icon: 'share', path: '/dashboard/shares' },
      { label: 'Notifications', icon: 'notifications', path: '/notifications' },
      { section: 'ACTIONS REQUISES' },
      { label: 'Demander une vérification', icon: 'verified', path: '/dashboard/documents' },
      { label: 'Mettre en vente un titre', icon: 'sell', path: '/dashboard/sell-title' },
      { label: 'Vérifier un document', icon: 'verified', path: '/dashboard/verify' },
      { section: 'SYSTÈME' },
      { label: "Journal d'activités", icon: 'receipt_long', path: '/dashboard/journal' },
      { label: 'Paramètres', icon: 'settings', path: '/dashboard/settings' },
    ],
  },
};

export function getRoleTheme(role) {
  return ROLE_THEMES[role] || ROLE_THEMES.USER;
}
